---
# git clone, head revision
- name: Repository Sucker
  url: https://dettgit.intra.ifm/scm/onx-testing/repositorysucker.git
  path: (root)
  command: git clone (url) (path)
# git clone and git checkout revision 171270415520f0fe49f79df26bbf96b49988b8b6
- name: Repository Sucker older revision
  url: https://dettgit.intra.ifm/scm/onx-testing/repositorysucker.git
  path: (root)/revision
  revision: 171270415520f0fe49f79df26bbf96b49988b8b6
  command: [git clone (url) (path), git checkout (revision)]
# svn checkout, head revision
- name: svn checkout head
  url: http://dettsvn.tt.de.ifm/svn/sy/libraries/esw/sandbox/dekoehac/quicklaunch
  path: (root)/ql
  command: [svn checkout --non-interactive --depth infinity (url) (path)]
# svn checkout older revision 229674
- name: svn checkout older revision
  url: http://dettsvn.tt.de.ifm/svn/sy/libraries/esw/sandbox/dekoehac/quicklaunch
  command: [svn checkout --non-interactive --depth infinity (url) (root)/ql/revision --revision (revision)]
  revision: 229674

